// <auto-generated />
using MVC2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231228112535_init 7")]
    partial class init7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC2.Models.Student", b =>
                {
                    b.Property<int>("RollNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RollNo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollNo"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordConfirmation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNo");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            RollNo = 1,
                            Email = "john.smith@example.com",
                            Name = "John Smith",
                            Password = "Pass123!",
                            PasswordConfirmation = "Pass123!",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            RollNo = 2,
                            Email = "alice.johnson@example.com",
                            Name = "Alice Johnson",
                            Password = "SecurePwd456",
                            PasswordConfirmation = "SecurePwd456",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            RollNo = 3,
                            Email = "bob.miller@example.com",
                            Name = "Bob Miller",
                            Password = "MySecretPwd789",
                            PasswordConfirmation = "MySecretPwd789",
                            PhoneNumber = "5551112233"
                        },
                        new
                        {
                            RollNo = 4,
                            Email = "emily.davis@example.com",
                            Name = "Emily Davis",
                            Password = "StrongPwd123",
                            PasswordConfirmation = "StrongPwd123",
                            PhoneNumber = "7778889999"
                        },
                        new
                        {
                            RollNo = 5,
                            Email = "michael.lee@example.com",
                            Name = "Michael Lee",
                            Password = "Pwd12345!",
                            PasswordConfirmation = "Pwd12345!",
                            PhoneNumber = "1112223333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
